version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: employee_management
      POSTGRES_USER: anele
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anele -d employee_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_USER: anele
      DB_PASSWORD: 12345
      DB_HOST: db          # matches service name
      DB_PORT: 5432
      DB_NAME: employee_management
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      sleep 10 &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: